In [58]:
_chromosomeLength = 8
_populatationCount = 10

GeneratePopulation()


([array([5, 6, 7, 0, 1, 3, 2, 4]),
  array([5, 7, 2, 1, 6, 0, 4, 3]),
  array([5, 2, 4, 6, 3, 1, 7, 0]),
  array([7, 1, 2, 6, 5, 4, 0, 3]),
  array([0, 1, 4, 7, 5, 3, 6, 2]),
  array([5, 2, 3, 7, 4, 0, 6, 1]),
  array([2, 6, 4, 1, 3, 7, 5, 0]),
  array([4, 1, 5, 3, 2, 7, 6, 0]),
  array([6, 0, 4, 2, 3, 7, 1, 5]),
  array([1, 6, 7, 4, 0, 5, 2, 3])],
 [6, 5, 3, 3, 3, 5, 5, 5, 6, 6])

In [57]:
def GeneratePopulation():
    population = list([])
    scores = list([])
    
    for i in range(_populatationCount): 
        population.append(GenerateChromosome())
        scores.append(Fit(population[i]))
        
    return population,scores

In [55]:
import numpy as np

def GenerateChromosome():
    initialState=np.arange(_chromosomeLength)
    
    np.random.shuffle(initialState)

    return initialState

In [44]:
def Fit(chromosome):
    rowColCollissionCount = _chromosomeLength - len(np.unique(chromosome))
    
    diagCollission = 0
    
    for i in range(_chromosomeLength):
        for j in range(i+1,_chromosomeLength):
            if(chromosome[i]+j-i==chromosome[j]):
                diagCollission+=1
                break
        for j in range(i+1,_chromosomeLength):
            if(chromosome[i]-j+i==chromosome[j]):
                diagCollission+=1
                break
     
    return rowColCollissionCount + diagCollission